// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Sanatorium;

#nullable disable

namespace Sanatorium.Migrations
{
    [DbContext(typeof(sanatoriumContext))]
    [Migration("20231212151542_migration")]
    partial class migration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Sanatorium.Alcoholic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool?>("Consciousness")
                        .HasColumnType("boolean")
                        .HasColumnName("consciousness");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("alcoholic", (string)null);
                });

            modelBuilder.Entity("Sanatorium.AlcoholicInspector", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AlcoholicId")
                        .HasColumnType("integer")
                        .HasColumnName("alcoholic_id");

                    b.Property<int?>("BedId")
                        .IsRequired()
                        .HasColumnType("integer");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("date");

                    b.Property<int?>("InspectorId")
                        .HasColumnType("integer")
                        .HasColumnName("inspector_id");

                    b.Property<int?>("State")
                        .HasColumnType("integer")
                        .HasColumnName("state");

                    b.HasKey("Id");

                    b.HasIndex("AlcoholicId");

                    b.HasIndex("BedId");

                    b.HasIndex("InspectorId");

                    b.ToTable("alcoholic_inspector", (string)null);
                });

            modelBuilder.Entity("Sanatorium.Bed", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("Number")
                        .HasColumnType("integer")
                        .HasColumnName("number");

                    b.HasKey("Id");

                    b.ToTable("bed", (string)null);
                });

            modelBuilder.Entity("Sanatorium.DrinkProcess", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("Date")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("date");

                    b.Property<int?>("DrinkTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("drink_type_id");

                    b.Property<int?>("GroupAlcoholicId")
                        .HasColumnType("integer")
                        .HasColumnName("group_alcoholic_id");

                    b.HasKey("Id");

                    b.ToTable("drink_process", (string)null);
                });

            modelBuilder.Entity("Sanatorium.DrinkType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AlcoholDegree")
                        .HasColumnType("integer")
                        .HasColumnName("alcohol_degree");

                    b.Property<string>("Name")
                        .HasColumnType("character varying")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("drink_type", (string)null);
                });

            modelBuilder.Entity("Sanatorium.Groupa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("GroupName")
                        .HasColumnType("character varying")
                        .HasColumnName("group_name");

                    b.HasKey("Id");

                    b.ToTable("groupa", (string)null);
                });

            modelBuilder.Entity("Sanatorium.GroupAlcoholic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AlcoholicId")
                        .HasColumnType("integer")
                        .HasColumnName("alcoholic_id");

                    b.Property<int?>("GroupId")
                        .HasColumnType("integer")
                        .HasColumnName("group_id");

                    b.HasKey("Id");

                    b.HasIndex("AlcoholicId");

                    b.HasIndex(new[] { "GroupId", "AlcoholicId" }, "group_alcoholic_group_id_alcoholic_id_key")
                        .IsUnique();

                    b.ToTable("group_alcoholic", (string)null);
                });

            modelBuilder.Entity("Sanatorium.Inspector", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("inspector", (string)null);
                });

            modelBuilder.Entity("Sanatorium.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("Birthdate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("birthdate");

                    b.Property<string>("Email")
                        .HasColumnType("character varying")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .HasColumnType("character varying")
                        .HasColumnName("name");

                    b.Property<string>("Password")
                        .HasColumnType("character varying")
                        .HasColumnName("password");

                    b.Property<string>("Sex")
                        .HasColumnType("character varying")
                        .HasColumnName("sex");

                    b.Property<string>("Surname")
                        .HasColumnType("character varying")
                        .HasColumnName("surname");

                    b.HasKey("Id");

                    b.ToTable("person", (string)null);
                });

            modelBuilder.Entity("Sanatorium.Alcoholic", b =>
                {
                    b.HasOne("Sanatorium.Person", "User")
                        .WithMany("Alcoholics")
                        .HasForeignKey("UserId")
                        .HasConstraintName("alcoholic_user_id_fkey");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Sanatorium.AlcoholicInspector", b =>
                {
                    b.HasOne("Sanatorium.Alcoholic", "Alcoholic")
                        .WithMany("AlcoholicInspectors")
                        .HasForeignKey("AlcoholicId")
                        .HasConstraintName("alcoholic_inspector_alcoholic_id_fkey");

                    b.HasOne("Sanatorium.Bed", "Bed")
                        .WithMany("AlcoholicInspectors")
                        .HasForeignKey("BedId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sanatorium.Inspector", "Inspector")
                        .WithMany("AlcoholicInspectors")
                        .HasForeignKey("InspectorId")
                        .HasConstraintName("alcoholic_inspector_inspector_id_fkey");

                    b.Navigation("Alcoholic");

                    b.Navigation("Bed");

                    b.Navigation("Inspector");
                });

            modelBuilder.Entity("Sanatorium.GroupAlcoholic", b =>
                {
                    b.HasOne("Sanatorium.Alcoholic", "Alcoholic")
                        .WithMany("GroupAlcoholics")
                        .HasForeignKey("AlcoholicId")
                        .HasConstraintName("group_alcoholic_alcoholic_id_fkey");

                    b.HasOne("Sanatorium.Groupa", "Group")
                        .WithMany("GroupAlcoholics")
                        .HasForeignKey("GroupId")
                        .HasConstraintName("group_alcoholic_group_id_fkey");

                    b.Navigation("Alcoholic");

                    b.Navigation("Group");
                });

            modelBuilder.Entity("Sanatorium.Inspector", b =>
                {
                    b.HasOne("Sanatorium.Person", "User")
                        .WithMany("Inspectors")
                        .HasForeignKey("UserId")
                        .HasConstraintName("inspector_user_id_fkey");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Sanatorium.Alcoholic", b =>
                {
                    b.Navigation("AlcoholicInspectors");

                    b.Navigation("GroupAlcoholics");
                });

            modelBuilder.Entity("Sanatorium.Bed", b =>
                {
                    b.Navigation("AlcoholicInspectors");
                });

            modelBuilder.Entity("Sanatorium.Groupa", b =>
                {
                    b.Navigation("GroupAlcoholics");
                });

            modelBuilder.Entity("Sanatorium.Inspector", b =>
                {
                    b.Navigation("AlcoholicInspectors");
                });

            modelBuilder.Entity("Sanatorium.Person", b =>
                {
                    b.Navigation("Alcoholics");

                    b.Navigation("Inspectors");
                });
#pragma warning restore 612, 618
        }
    }
}
